# Generated by Django 2.1.7 on 2019-03-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
